### PR TITLE
ox logo but cooler

### PR DESCRIPTION
**Pull request by SirUela**
Screen Shot 2022-01-14 at 8 46 16 AM

### CODE REVIEW

**Comment by paganotoni** [comment]
@SirUela I wonder. which terminals does this support?

**Comment by SirUela** [comment]
Most UNIX based terminals supports ANSI escape sequences, but for windows I think is only → 10; If it's not possible, that's ok.

**Comment by paganotoni** [comment]
Could we do the dark version of it ?

**Comment by paganotoni** [comment]
CleanShot 2022-01-14 at 14 37 56

**Comment by SirUela** [comment]
Yes, there is also an only ASCII version, if the ANSI one is a problem
Screen Shot 2022-01-14 at 2 50 16 PM

**Comment by paganotoni** [comment]
Love it. Lets go with the only ASCII one. THanks @SirUela !

**Comment by SirUela** [comment]
All set!

**Comment by paganotoni** [comment]
Thanks @SirUela !

**Pull request merged**
